import type { Metadata } from "next";
import { Inter, Sora, Source_Code_Pro, Space_Grotesk } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const sora = Sora({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  variable: "--font-sora",
  display: "swap",
});
const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-code",
  display: "swap",
});
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-grotesk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Brainwave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          type="image/svg+xml"
          href="/assets/brainwave-symbol.svg"
        />
      </head>
      <body
        className={`${sora.variable} ${sourceCodePro.variable} ${spaceGrotesk.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
